apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loki-parser.fullname" . }}-role
  labels:
    {{- include "loki-parser.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]