apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "loki-parser.fullname" . }}-rolebinding
  labels:
    {{- include "loki-parser.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "loki-parser.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "loki-parser.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io